-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "zsh" },
--   callback = function()
--     -- let treesitter use bash highlight for zsh files as well
--     require("nvim-treesitter.highlight").attach(0, "bash")
--     vim.lsp.start({
--       name = "bash-language-server",
--       cmd = { "bash-language-server", "start" },
--     })
--   end,
-- })
